
import java.awt.HeadlessException;
import java.awt.List;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Randald
 */
public class WindowSelectionGame extends javax.swing.JFrame {
    //NavBar will be used to keep the NavBar events..
    private boolean navBar, navBar2;
    Player userToSelect  = ListPlayersRegistered.getInstance().start;
    private static ArrayList<String> playersThatWillPlay = new ArrayList<String>(4);
    private static int numberOfPlayersSelected = 1;
    /**
     * Creates new form Load
     * @param auxName
     */
    public WindowSelectionGame(String auxName) {
        
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);  //set full size
        Boolean navBar = false;                 //set nav bar = false because the navBar will be close when the user start the game         
        principalPanel.setSize(0,0);            // set panel for load (0,0)
        principalPanel2.setSize(0,0);           // set panel for new game (0,0)
        playersThatWillPlay.add("");
        actualPlayerName2.setText(auxName);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalImage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        butonLoadGame = new javax.swing.JButton();
        butonNewGame = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        actualPlayerName2 = new javax.swing.JLabel();
        principalPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        laberUser1 = new javax.swing.JLabel();
        laberUser2 = new javax.swing.JLabel();
        labelPassword2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        buttonSingIn1 = new javax.swing.JButton();
        principalPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        numberPlayers = new javax.swing.JComboBox<>();
        buttonNewGame = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelWins = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        infoPlayer = new javax.swing.JLabel();
        countPlayerSelected = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        principalImage.setBackground(new java.awt.Color(102, 0, 255));
        principalImage.setFont(new java.awt.Font("Script MT Bold", 3, 14)); // NOI18N
        principalImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/navBar.jpg"))); // NOI18N
        getContentPane().add(principalImage);
        principalImage.setBounds(490, 0, 1530, 1080);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/l_oad.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 300, 96, 89);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 460, 96, 95);

        butonLoadGame.setBackground(new java.awt.Color(102, 0, 255));
        butonLoadGame.setFont(new java.awt.Font("Script MT Bold", 3, 18)); // NOI18N
        butonLoadGame.setForeground(new java.awt.Color(255, 255, 255));
        butonLoadGame.setText("Load");
        butonLoadGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonLoadGameActionPerformed(evt);
            }
        });
        jPanel1.add(butonLoadGame);
        butonLoadGame.setBounds(250, 310, 91, 60);

        butonNewGame.setBackground(new java.awt.Color(102, 0, 255));
        butonNewGame.setFont(new java.awt.Font("Script MT Bold", 3, 18)); // NOI18N
        butonNewGame.setForeground(new java.awt.Color(255, 255, 255));
        butonNewGame.setText("New");
        butonNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonNewGameActionPerformed(evt);
            }
        });
        jPanel1.add(butonNewGame);
        butonNewGame.setBounds(250, 470, 91, 60);

        jLabel6.setFont(new java.awt.Font("Script MT Bold", 3, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 255));
        jLabel6.setText("Welcome");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(130, 50, 240, 90);

        actualPlayerName2.setFont(new java.awt.Font("Script MT Bold", 3, 36)); // NOI18N
        actualPlayerName2.setForeground(new java.awt.Color(102, 0, 255));
        actualPlayerName2.setLabelFor(actualPlayerName2);
        jPanel1.add(actualPlayerName2);
        actualPlayerName2.setBounds(130, 170, 210, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 490, 1080);

        principalPanel.setBackground(new java.awt.Color(20, 0, 169));
        principalPanel.setMaximumSize(new java.awt.Dimension(1530, 1080));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userGames.png"))); // NOI18N

        jScrollPane1.setViewportView(jList1);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        laberUser1.setBackground(new java.awt.Color(102, 0, 255));
        laberUser1.setFont(new java.awt.Font("Script MT Bold", 3, 24)); // NOI18N
        laberUser1.setForeground(new java.awt.Color(102, 0, 255));
        laberUser1.setText("Update your data");

        laberUser2.setBackground(new java.awt.Color(255, 255, 255));
        laberUser2.setFont(new java.awt.Font("Script MT Bold", 3, 24)); // NOI18N
        laberUser2.setForeground(new java.awt.Color(255, 255, 255));
        laberUser2.setText("New name:");

        labelPassword2.setFont(new java.awt.Font("Script MT Bold", 3, 24)); // NOI18N
        labelPassword2.setForeground(new java.awt.Color(255, 255, 255));
        labelPassword2.setText("New password :");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        buttonSingIn1.setBackground(new java.awt.Color(255, 255, 255));
        buttonSingIn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/finalAccep.png"))); // NOI18N
        buttonSingIn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonSingIn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSingIn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(buttonSingIn1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(laberUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelPassword2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(laberUser2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(laberUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(laberUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttonSingIn1)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout principalPanelLayout = new javax.swing.GroupLayout(principalPanel);
        principalPanel.setLayout(principalPanelLayout);
        principalPanelLayout.setHorizontalGroup(
            principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(15, 15, 15)
                .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1035, 1035, 1035))
        );
        principalPanelLayout.setVerticalGroup(
            principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        getContentPane().add(principalPanel);
        principalPanel.setBounds(490, 0, 1530, 660);

        principalPanel2.setBackground(new java.awt.Color(20, 0, 169));
        principalPanel2.setMaximumSize(new java.awt.Dimension(1530, 1080));
        principalPanel2.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/check1.png"))); // NOI18N
        principalPanel2.add(jLabel7);
        jLabel7.setBounds(20, 20, 96, 96);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(102, 0, 255));

        numberPlayers.setBackground(new java.awt.Color(0, 0, 0));
        numberPlayers.setFont(new java.awt.Font("Script MT Bold", 1, 14)); // NOI18N
        numberPlayers.setForeground(new java.awt.Color(102, 0, 255));
        numberPlayers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2 Players", "3 Players", "4 Players" }));

        buttonNewGame.setBackground(new java.awt.Color(0, 0, 0));
        buttonNewGame.setFont(new java.awt.Font("Script MT Bold", 1, 14)); // NOI18N
        buttonNewGame.setForeground(new java.awt.Color(102, 0, 255));
        buttonNewGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/finalAccep.png"))); // NOI18N
        buttonNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewGameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        jLabel5.setText("Select the players");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(numberPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonNewGame)
                        .addGap(47, 47, 47))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numberPlayers)
                    .addComponent(buttonNewGame, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                .addGap(131, 131, 131))
        );

        principalPanel2.add(jPanel2);
        jPanel2.setBounds(140, 120, 312, 300);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setForeground(new java.awt.Color(102, 0, 255));

        jLabel8.setFont(new java.awt.Font("Script MT Bold", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Name :");

        labelName.setFont(new java.awt.Font("Script MT Bold", 3, 14)); // NOI18N
        labelName.setForeground(new java.awt.Color(255, 255, 255));
        labelName.setText("name");

        jLabel10.setFont(new java.awt.Font("Script MT Bold", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Wins :");

        labelWins.setFont(new java.awt.Font("Script MT Bold", 3, 14)); // NOI18N
        labelWins.setForeground(new java.awt.Color(255, 255, 255));
        labelWins.setText("wins");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(102, 0, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/goBack.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(102, 0, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/finalAccep.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(102, 0, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/goNext.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        infoPlayer.setFont(new java.awt.Font("Script MT Bold", 3, 16)); // NOI18N
        infoPlayer.setForeground(new java.awt.Color(102, 0, 255));
        infoPlayer.setText("Players selected:");

        countPlayerSelected.setFont(new java.awt.Font("Script MT Bold", 0, 14)); // NOI18N
        countPlayerSelected.setForeground(new java.awt.Color(102, 0, 255));
        countPlayerSelected.setText("1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(infoPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(countPlayerSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelWins, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(19, 19, 19)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infoPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(countPlayerSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelName, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(labelWins, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE))
        );

        principalPanel2.add(jPanel3);
        jPanel3.setBounds(140, 460, 310, 240);

        getContentPane().add(principalPanel2);
        principalPanel2.setBounds(490, 0, 1530, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void butonNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonNewGameActionPerformed
        //It check if the panel for new game is open or not
        if (navBar2 == true){                //If is open
            principalPanel2.setSize(0, 0);   //the panel for new game will change to close 
            navBar2 = false;                 //it change the NavBar 2 status
            principalPanel.setSize(0, 0);   //the panel for load game will change to close
            navBar = false;                 //it change the NavBar 1 status
        } 
        else{ //if navBar is close
            principalPanel2.setSize(550, 1080);//the panel for new game will change to Open
            navBar2 = true;                    // it change the NavBar 2 status
            principalPanel.setSize(0, 0);      //the panel for load game will change to close
            navBar = false;                    //it change the NavBar 1 status
        }
    }//GEN-LAST:event_butonNewGameActionPerformed

    private void butonLoadGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonLoadGameActionPerformed
        //It check if the panel for load game is open or not
        if (navBar == true){                //If is open the panel
            principalPanel.setSize(0, 0); //the load panel will change to close 
            navBar = false;                 //it change the NavBar status
            principalPanel2.setSize(0, 0);  //the new game panel  will change to close
            navBar2 = false;                //it change the NavBar 2 status
        } 
        else{ //if navBar is close
            principalPanel.setSize(550, 1080);//the principal panel will change to Open
            navBar = true;                   // it change the NavBar status
            principalPanel2.setSize(0, 0);   //the new game panel will change to close
            navBar2 = false;                 //it change the NavBar 2 status
        }
    }//GEN-LAST:event_butonLoadGameActionPerformed

    private void buttonNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewGameActionPerformed

        if (numberPlayers.getSelectedItem() == "2 Players") {          //check if is two players selected
            if (numberOfPlayersSelected >= 2) {
                ListPlayersGaming.getInstance().setNumberOfGamers(2);
                ListPlayersGaming.getInstance().makeListofTwoPlayers();    //add user 1 information
                ListPlayersGaming.getInstance().player2.setName(playersThatWillPlay.get(1));
                WindowStartGame newWindows = new WindowStartGame();        //close This windows and go to Start Game Windows 
                newWindows.setVisible(true);                               //set visible the new windows
                this.dispose();                                            //Destroy the actual windows
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "You need to select 1 player to play agains.");
            }
        }
        

        else if (numberPlayers.getSelectedItem() == "3 Players") {     //check if is tree players selected
            if (numberOfPlayersSelected >= 3) {
                ListPlayersGaming.getInstance().setNumberOfGamers(3);
                ListPlayersGaming.getInstance().makeListofThreePlayers();  //add user 1 information
                ListPlayersGaming.getInstance().player2.setName(playersThatWillPlay.get(1));
                ListPlayersGaming.getInstance().player3.setName(playersThatWillPlay.get(2));
                WindowStartGame newWindows = new WindowStartGame();        //close This windows and go to Start Game Windows 
                newWindows.setVisible(true);                               //set visible the new windows
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "You need to select 2 players to play agains.");
            }
        } 
        else if (numberPlayers.getSelectedItem() == "4 Players") { 
            if (numberOfPlayersSelected >= 4) {
                ListPlayersGaming.getInstance().setNumberOfGamers(4);
                ListPlayersGaming.getInstance().makeListofFourPlayers();
                ListPlayersGaming.getInstance().player2.setName(playersThatWillPlay.get(1));
                ListPlayersGaming.getInstance().player3.setName(playersThatWillPlay.get(2));
                ListPlayersGaming.getInstance().player4.setName(playersThatWillPlay.get(3));
                WindowStartGame newWindows = new WindowStartGame();        //close This windows and go to Start Game Windows 
                newWindows.setVisible(true);                               //set visible the new windows
                this.dispose();                                            //Destroy the actual windows
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "You need to select 3 players to play agains.");
            }
        }
            

    }//GEN-LAST:event_buttonNewGameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String n = ListPlayersGaming.getInstance().getActualUser().getName();
        playersThatWillPlay.set(0, n);
        searchPlayerVersus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        userToSelect = userToSelect.sig;
        labelName.setText(userToSelect.getName());
        labelWins.setText(Integer.toString(userToSelect.getWins()));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userToSelect = userToSelect.ant;
        labelName.setText(userToSelect.getName());
        labelWins.setText(Integer.toString(userToSelect.getWins()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonSingIn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSingIn1ActionPerformed
        // TODO add your handling code here:
        String newName = jTextField1.getText();
        String newPassword = jTextField2.getText();
        ListPlayersRegistered.getInstance().editSelfData(newName, newName, newPassword);  
        ListPlayersGaming.getInstance().actualUser.setName(newName);
        principalPanel.setSize(0,0);
        navBar = false;
        navBar2 = false;
        actualPlayerName2.setText(newName);
        
    }//GEN-LAST:event_buttonSingIn1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actualPlayerName2;
    private javax.swing.JButton butonLoadGame;
    private javax.swing.JButton butonNewGame;
    private javax.swing.JButton buttonNewGame;
    private javax.swing.JButton buttonSingIn1;
    private javax.swing.JLabel countPlayerSelected;
    private javax.swing.JLabel infoPlayer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPassword2;
    private javax.swing.JLabel labelWins;
    private javax.swing.JLabel laberUser1;
    private javax.swing.JLabel laberUser2;
    private javax.swing.JComboBox<String> numberPlayers;
    private javax.swing.JLabel principalImage;
    private javax.swing.JPanel principalPanel;
    private javax.swing.JPanel principalPanel2;
    // End of variables declaration//GEN-END:variables

    
   
    public void searchPlayerVersus(){
        
        if(playersThatWillPlay.contains(labelName.getText())){
            JOptionPane.showMessageDialog(rootPane, "That player is already playing");
        }
        else if(numberOfPlayersSelected > 3 ){
            JOptionPane.showMessageDialog(rootPane, "You can not select more than 4 players.");
        }
        else{
            numberOfPlayersSelected++;
            countPlayerSelected.setText(Integer.toString(numberOfPlayersSelected));
            playersThatWillPlay.add(labelName.getText());
            JOptionPane.showMessageDialog(rootPane, labelName.getText() + " selected.");
        }
    }
   
}
