/* * * * * * * * * * * * * * * * * * * * * * * *
 * Instituto Tecnológico de Costa Rica         *
 * Data structures                             *
 * 1st Project: Domino´s game                  *
 * by: Fabián Zamora R. and Randald Villegas B.*
 * * * * * * * * * * * * * * * * * * * * * * * */


import javax.swing.JOptionPane;

/**
 *
 * @author Fabián
 */
public class WindowAdmin extends javax.swing.JFrame {

    /**
     * Creates new form WindowAdmin
     */
    public WindowAdmin() {
        super("Domino's Administration Menu");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelTextPassword = new javax.swing.JLabel();
        labelTextName = new javax.swing.JLabel();
        TextFieldUserToEdit = new javax.swing.JTextField();
        labelUserToEdit = new javax.swing.JLabel();
        labelNewName = new javax.swing.JLabel();
        labelNewPassword = new javax.swing.JLabel();
        changeWins = new javax.swing.JLabel();
        TextFieldChangeWins = new javax.swing.JTextField();
        TextFieldNewPassword = new javax.swing.JTextField();
        TextFieldNewName = new javax.swing.JTextField();
        buttonModifyUser = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        buttonAddUser = new javax.swing.JButton();
        buttonBack = new javax.swing.JButton();
        labelSearchUser = new javax.swing.JLabel();
        TextFieldUserDelete = new javax.swing.JTextField();
        buttonSearch = new javax.swing.JButton();
        labelTextResult = new javax.swing.JLabel();
        buttonDeleteUser = new javax.swing.JButton();
        labelResult = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextFieldPassword = new javax.swing.JTextField();
        TextFieldName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        buttonLeft = new javax.swing.JButton();
        buttonStart = new javax.swing.JButton();
        buttonEnd = new javax.swing.JButton();
        buttonRight = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progra1/Images/dominobbbb.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1044, 648));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        labelTextPassword.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        labelTextPassword.setForeground(new java.awt.Color(255, 255, 255));
        labelTextPassword.setText("Password:");
        jPanel2.add(labelTextPassword);
        labelTextPassword.setBounds(12, 94, 81, 24);

        labelTextName.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        labelTextName.setForeground(new java.awt.Color(255, 255, 255));
        labelTextName.setText("Name:");
        jPanel2.add(labelTextName);
        labelTextName.setBounds(32, 52, 44, 30);
        jPanel2.add(TextFieldUserToEdit);
        TextFieldUserToEdit.setBounds(164, 214, 80, 30);

        labelUserToEdit.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        labelUserToEdit.setForeground(new java.awt.Color(255, 255, 255));
        labelUserToEdit.setText("User to edit:");
        jPanel2.add(labelUserToEdit);
        labelUserToEdit.setBounds(36, 213, 110, 30);

        labelNewName.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        labelNewName.setForeground(new java.awt.Color(255, 255, 255));
        labelNewName.setText("New Name:");
        jPanel2.add(labelNewName);
        labelNewName.setBounds(65, 266, 81, 20);

        labelNewPassword.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        labelNewPassword.setForeground(new java.awt.Color(255, 255, 255));
        labelNewPassword.setText("New Password:");
        jPanel2.add(labelNewPassword);
        labelNewPassword.setBounds(36, 315, 110, 20);

        changeWins.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        changeWins.setForeground(new java.awt.Color(255, 255, 255));
        changeWins.setText("Change Wins to:");
        jPanel2.add(changeWins);
        changeWins.setBounds(22, 363, 130, 20);

        TextFieldChangeWins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldChangeWinsActionPerformed(evt);
            }
        });
        jPanel2.add(TextFieldChangeWins);
        TextFieldChangeWins.setBounds(164, 359, 80, 30);
        jPanel2.add(TextFieldNewPassword);
        TextFieldNewPassword.setBounds(164, 311, 80, 30);
        jPanel2.add(TextFieldNewName);
        TextFieldNewName.setBounds(164, 262, 80, 30);

        buttonModifyUser.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        buttonModifyUser.setText("Edit");
        buttonModifyUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModifyUserActionPerformed(evt);
            }
        });
        jPanel2.add(buttonModifyUser);
        buttonModifyUser.setBounds(164, 415, 80, 30);

        jButton1.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jButton1.setText("See");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(390, 360, 57, 23);

        buttonAddUser.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        buttonAddUser.setText("Add User");
        buttonAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddUserActionPerformed(evt);
            }
        });
        jPanel2.add(buttonAddUser);
        buttonAddUser.setBounds(88, 133, 160, 30);

        buttonBack.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        buttonBack.setText("<<");
        buttonBack.setToolTipText("");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });
        jPanel2.add(buttonBack);
        buttonBack.setBounds(22, 415, 49, 30);

        labelSearchUser.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        labelSearchUser.setForeground(new java.awt.Color(255, 255, 255));
        labelSearchUser.setText("Search user:");
        jPanel2.add(labelSearchUser);
        labelSearchUser.setBounds(600, 70, 108, 14);

        TextFieldUserDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldUserDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(TextFieldUserDelete);
        TextFieldUserDelete.setBounds(710, 60, 116, 30);

        buttonSearch.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        buttonSearch.setText("Search");
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });
        jPanel2.add(buttonSearch);
        buttonSearch.setBounds(710, 110, 116, 30);

        labelTextResult.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        labelTextResult.setForeground(new java.awt.Color(255, 255, 255));
        labelTextResult.setText("Password:");
        jPanel2.add(labelTextResult);
        labelTextResult.setBounds(620, 160, 80, 23);

        buttonDeleteUser.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        buttonDeleteUser.setText("Delete user");
        buttonDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteUserActionPerformed(evt);
            }
        });
        jPanel2.add(buttonDeleteUser);
        buttonDeleteUser.setBounds(710, 210, 121, 30);

        labelResult.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(labelResult);
        labelResult.setBounds(710, 160, 122, 30);

        jLabel2.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Number of registered players:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(320, 300, 203, 44);
        jPanel2.add(TextFieldPassword);
        TextFieldPassword.setBounds(88, 92, 160, 30);
        jPanel2.add(TextFieldName);
        TextFieldName.setBounds(88, 53, 160, 30);

        jLabel1.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel1);
        jLabel1.setBounds(540, 300, 50, 44);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("MS Gothic", 1, 11)); // NOI18N
        jLabel3.setText(" Registered games");

        buttonLeft.setFont(new java.awt.Font("MS Gothic", 1, 11)); // NOI18N
        buttonLeft.setText("<<");

        buttonStart.setFont(new java.awt.Font("MS Gothic", 1, 11)); // NOI18N
        buttonStart.setText("Start");

        buttonEnd.setFont(new java.awt.Font("MS Gothic", 1, 11)); // NOI18N
        buttonEnd.setText("End");

        buttonRight.setFont(new java.awt.Font("MS Gothic", 1, 11)); // NOI18N
        buttonRight.setText(">>");

        jList1.setFont(new java.awt.Font("Dialog", 2, 11)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Date", "Winner" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(buttonLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRight))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonStart)
                    .addComponent(buttonEnd)
                    .addComponent(buttonLeft)
                    .addComponent(buttonRight))
                .addGap(11, 11, 11))
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(290, 50, 270, 150);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1070, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldUserDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldUserDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldUserDeleteActionPerformed

    private void buttonDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteUserActionPerformed
        // TODO add your handling code here:
        if(TextFieldUserDelete.getText().isEmpty())
            JOptionPane.showMessageDialog(rootPane, "Empty field");
        else{
            String name = TextFieldUserDelete.getText();
            ListPlayersRegistered.getInstance().deletePlayer(name);
            JOptionPane.showMessageDialog(rootPane, "Player " + name + " succesfully deleted.");
            TextFieldUserDelete.setText("");      
       }
    }//GEN-LAST:event_buttonDeleteUserActionPerformed

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        // TODO add your handling code here:
        if(TextFieldUserDelete.getText().isEmpty())
            JOptionPane.showMessageDialog(rootPane, "Type a player to eliminate");
        else{
            Player userX = ListPlayersRegistered.getInstance().searchPlayer(TextFieldUserDelete.getText());
            if(userX == null)
                labelResult.setText("No matches found");
            else{
                labelResult.setText(userX.getPassword());
            }
        }
        
    }//GEN-LAST:event_buttonSearchActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddUserActionPerformed
        // TODO add your handling code here:
        if(TextFieldName.getText().isEmpty() | TextFieldPassword.getText().isEmpty())
            JOptionPane.showMessageDialog(rootPane, "Empty field");
        else{
            String nameX = TextFieldName.getText();
            String passwordX = TextFieldPassword.getText();
            ListPlayersRegistered.getInstance().insertFinal(nameX, passwordX, 0);
            TextFieldName.setText("");
            TextFieldPassword.setText("");
            JOptionPane.showMessageDialog(rootPane, "Player " + nameX + "successfully added to the system.");
        }
    }//GEN-LAST:event_buttonAddUserActionPerformed

    private void buttonModifyUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModifyUserActionPerformed
        // TODO add your handling code here:
        if(TextFieldUserToEdit.getText().isEmpty() | TextFieldNewName.getText().isEmpty() | TextFieldNewPassword.getText().isEmpty() |  TextFieldChangeWins.getText().isEmpty())
            JOptionPane.showMessageDialog(rootPane, "Empty field");
        else{
            String name = TextFieldUserToEdit.getText();
            String newName = TextFieldNewName.getText();
            String password = TextFieldNewPassword.getText();
            int wins = Integer.parseInt(TextFieldChangeWins.getText());
            ListPlayersRegistered.getInstance().editPlayer(name, newName, password, wins);
            TextFieldUserToEdit.setText("");
            TextFieldNewName.setText("");
            TextFieldNewPassword.setText("");
            TextFieldChangeWins.setText("");
            JOptionPane.showMessageDialog(rootPane, "Player " + name + " successfully edited.");
        }
    }//GEN-LAST:event_buttonModifyUserActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jLabel1.setText(Integer.toString(ListPlayersRegistered.getInstance().lenghtList()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TextFieldChangeWinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldChangeWinsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldChangeWinsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFieldChangeWins;
    private javax.swing.JTextField TextFieldName;
    private javax.swing.JTextField TextFieldNewName;
    private javax.swing.JTextField TextFieldNewPassword;
    private javax.swing.JTextField TextFieldPassword;
    private javax.swing.JTextField TextFieldUserDelete;
    private javax.swing.JTextField TextFieldUserToEdit;
    private javax.swing.JButton buttonAddUser;
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonDeleteUser;
    private javax.swing.JButton buttonEnd;
    private javax.swing.JButton buttonLeft;
    private javax.swing.JButton buttonModifyUser;
    private javax.swing.JButton buttonRight;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JButton buttonStart;
    private javax.swing.JLabel changeWins;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNewName;
    private javax.swing.JLabel labelNewPassword;
    private javax.swing.JLabel labelResult;
    private javax.swing.JLabel labelSearchUser;
    private javax.swing.JLabel labelTextName;
    private javax.swing.JLabel labelTextPassword;
    private javax.swing.JLabel labelTextResult;
    private javax.swing.JLabel labelUserToEdit;
    // End of variables declaration//GEN-END:variables
}
