
import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Randald
 */
public class WindowSelectionGame extends javax.swing.JFrame {
    //NavBar will be used to keep the NavBar events..
    private boolean navBar, navBar2;
    Player userToSelect  = ListPlayersRegistered.getInstance().start;
    ArrayList<String> playersThatWillPlay = new ArrayList<String>();
    int numberOfPlayersSelected = 1;
    /**
     * Creates new form Load
     */
    public WindowSelectionGame() {
        initComponents();
        
        
        this.setExtendedState(MAXIMIZED_BOTH);  //set full size
       
        
        Boolean navBar = false;                 //set nav bar = false because the navBar will be close when the user start the game         
        principalPanel.setSize(0,0);            // set panel for load (0,0)
        principalPanel2.setSize(0,0);           // set panel for new game (0,0)
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalImage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        butonLoadGame = new javax.swing.JButton();
        butonNewGame = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        actualPlayerName2 = new javax.swing.JLabel();
        principalPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        principalPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        numberPlayers = new javax.swing.JComboBox<>();
        buttonNewGame = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelWins = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        labelplayersSelected = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        principalImage.setBackground(new java.awt.Color(84, 0, 255));
        principalImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/domino.jpg"))); // NOI18N
        getContentPane().add(principalImage);
        principalImage.setBounds(490, 0, 1530, 1080);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Script MT Bold", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(32, 124, 2));
        jLabel1.setText("THE DOMINO'S GAME");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 30, 280, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/load.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 300, 96, 89);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/new.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 460, 96, 95);

        butonLoadGame.setBackground(new java.awt.Color(0, 0, 0));
        butonLoadGame.setFont(new java.awt.Font("Script MT Bold", 3, 18)); // NOI18N
        butonLoadGame.setForeground(new java.awt.Color(255, 255, 255));
        butonLoadGame.setText("Load");
        butonLoadGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonLoadGameActionPerformed(evt);
            }
        });
        jPanel1.add(butonLoadGame);
        butonLoadGame.setBounds(250, 310, 91, 55);

        butonNewGame.setBackground(new java.awt.Color(0, 0, 0));
        butonNewGame.setFont(new java.awt.Font("Script MT Bold", 3, 18)); // NOI18N
        butonNewGame.setForeground(new java.awt.Color(255, 255, 255));
        butonNewGame.setText("New");
        butonNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonNewGameActionPerformed(evt);
            }
        });
        jPanel1.add(butonNewGame);
        butonNewGame.setBounds(250, 470, 91, 60);

        jLabel6.setFont(new java.awt.Font("Script MT Bold", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(32, 124, 2));
        jLabel6.setText("WELCOME ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(160, 100, 140, 40);

        actualPlayerName2.setFont(new java.awt.Font("Script MT Bold", 3, 24)); // NOI18N
        actualPlayerName2.setForeground(new java.awt.Color(32, 124, 2));
        actualPlayerName2.setText("PLAYER ");
        jPanel1.add(actualPlayerName2);
        actualPlayerName2.setBounds(160, 170, 140, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 490, 1080);

        principalPanel.setBackground(new java.awt.Color(20, 0, 169));
        principalPanel.setMaximumSize(new java.awt.Dimension(1530, 1080));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userGames.png"))); // NOI18N

        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout principalPanelLayout = new javax.swing.GroupLayout(principalPanel);
        principalPanel.setLayout(principalPanelLayout);
        principalPanelLayout.setHorizontalGroup(
            principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalPanelLayout.createSequentialGroup()
                .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(principalPanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel4))
                    .addGroup(principalPanelLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(422, Short.MAX_VALUE))
        );
        principalPanelLayout.setVerticalGroup(
            principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        getContentPane().add(principalPanel);
        principalPanel.setBounds(490, 0, 1530, 660);

        principalPanel2.setBackground(new java.awt.Color(20, 0, 169));
        principalPanel2.setMaximumSize(new java.awt.Dimension(1530, 1080));
        principalPanel2.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/check1.png"))); // NOI18N
        principalPanel2.add(jLabel7);
        jLabel7.setBounds(20, 20, 96, 96);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        numberPlayers.setBackground(new java.awt.Color(3, 105, 49));
        numberPlayers.setFont(new java.awt.Font("Script MT Bold", 1, 14)); // NOI18N
        numberPlayers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2 Players", "3 Players", "4 Players" }));

        buttonNewGame.setBackground(new java.awt.Color(3, 105, 49));
        buttonNewGame.setFont(new java.awt.Font("Script MT Bold", 1, 14)); // NOI18N
        buttonNewGame.setForeground(new java.awt.Color(255, 255, 255));
        buttonNewGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/check.png"))); // NOI18N
        buttonNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewGameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        jLabel5.setText("Select the players");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(numberPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonNewGame)
                        .addGap(47, 47, 47))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numberPlayers)
                    .addComponent(buttonNewGame, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                .addGap(131, 131, 131))
        );

        principalPanel2.add(jPanel2);
        jPanel2.setBounds(140, 120, 312, 300);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jLabel8.setText("Name :");

        labelName.setText("name");

        jLabel10.setText("Wins :");

        labelWins.setText("wins");

        jButton1.setBackground(new java.awt.Color(3, 105, 49));
        jButton1.setText("<<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(3, 105, 49));
        jButton2.setText("Select");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(3, 105, 49));
        jButton3.setText(">>");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelWins)
                            .addComponent(labelName))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(labelName))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelWins)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        principalPanel2.add(jPanel3);
        jPanel3.setBounds(140, 440, 310, 200);

        jLabel9.setText("Players selected:");
        principalPanel2.add(jLabel9);
        jLabel9.setBounds(150, 640, 90, 40);

        labelplayersSelected.setText("1");
        principalPanel2.add(labelplayersSelected);
        labelplayersSelected.setBounds(250, 650, 40, 20);

        getContentPane().add(principalPanel2);
        principalPanel2.setBounds(490, 0, 1530, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butonNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonNewGameActionPerformed
        //It check if the panel for new game is open or not
        if (navBar2 == true){                //If is open
            principalPanel2.setSize(0, 0);   //the panel for new game will change to close 
            navBar2 = false;                 //it change the NavBar 2 status
            principalPanel.setSize(0, 0);   //the panel for load game will change to close
            navBar = false;                 //it change the NavBar 1 status
        } 
        else{ //if navBar is close
            principalPanel2.setSize(550, 1080);//the panel for new game will change to Open
            navBar2 = true;                    // it change the NavBar 2 status
            principalPanel.setSize(0, 0);      //the panel for load game will change to close
            navBar = false;                    //it change the NavBar 1 status
        }
    }//GEN-LAST:event_butonNewGameActionPerformed

    private void butonLoadGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonLoadGameActionPerformed
        //It check if the panel for load game is open or not
        if (navBar == true){                //If is open the panel
            principalPanel.setSize(0, 0); //the load panel will change to close 
            navBar = false;                 //it change the NavBar status
            principalPanel2.setSize(0, 0);  //the new game panel  will change to close
            navBar2 = false;                //it change the NavBar 2 status
        } 
        else{ //if navBar is close
            principalPanel.setSize(550, 1080);//the principal panel will change to Open
            navBar = true;                   // it change the NavBar status
            principalPanel2.setSize(0, 0);   //the new game panel will change to close
            navBar2 = false;                 //it change the NavBar 2 status
        }
    }//GEN-LAST:event_butonLoadGameActionPerformed

    private void buttonNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewGameActionPerformed

        if (numberPlayers.getSelectedItem() == "2 Players") {          //check if is two players selected
            if (numberOfPlayersSelected == 2) {
                ListPlayersGaming.getInstance().setNumberOfGamers(2);
                ListPlayersGaming.getInstance().makeListofTwoPlayers();    //add user 1 information
                ListPlayersGaming.getInstance().player2.setName(playersThatWillPlay.get(0));
                WindowStartGame newWindows = new WindowStartGame();        //close This windows and go to Start Game Windows 
                newWindows.setVisible(true);                               //set visible the new windows
                this.dispose();                                            //Destroy the actual windows
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "You need to select 1 player to play agains.");
            }
        }
        

        else if (numberPlayers.getSelectedItem() == "3 Players") {     //check if is tree players selected
            if (numberOfPlayersSelected == 3) {
                ListPlayersGaming.getInstance().setNumberOfGamers(3);
                ListPlayersGaming.getInstance().makeListofThreePlayers();  //add user 1 information
                ListPlayersGaming.getInstance().player2.setName(playersThatWillPlay.get(0));
                ListPlayersGaming.getInstance().player3.setName(playersThatWillPlay.get(1));
                WindowStartGame newWindows = new WindowStartGame();        //close This windows and go to Start Game Windows 
                newWindows.setVisible(true);                               //set visible the new windows
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "You need to select 2 players to play agains.");
            }
        } 
        else if (numberPlayers.getSelectedItem() == "4 Players") { 
            if (numberOfPlayersSelected == 4) {
                ListPlayersGaming.getInstance().setNumberOfGamers(4);
                ListPlayersGaming.getInstance().makeListofFourPlayers();
                ListPlayersGaming.getInstance().player2.setName(playersThatWillPlay.get(0));
                ListPlayersGaming.getInstance().player3.setName(playersThatWillPlay.get(1));
                ListPlayersGaming.getInstance().player2.setName(playersThatWillPlay.get(2));
                WindowStartGame newWindows = new WindowStartGame();        //close This windows and go to Start Game Windows 
                newWindows.setVisible(true);                               //set visible the new windows
                this.dispose();                                            //Destroy the actual windows
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "You need to select 3 players to play agains.");
            }
        }
            

    }//GEN-LAST:event_buttonNewGameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        searchPlayerVersus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        userToSelect = userToSelect.sig;
        labelName.setText(userToSelect.getName());
        labelWins.setText(Integer.toString(userToSelect.getWins()));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userToSelect = userToSelect.ant;
        labelName.setText(userToSelect.getName());
        labelWins.setText(Integer.toString(userToSelect.getWins()));
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actualPlayerName2;
    private javax.swing.JButton butonLoadGame;
    private javax.swing.JButton butonNewGame;
    private javax.swing.JButton buttonNewGame;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelWins;
    private javax.swing.JLabel labelplayersSelected;
    private javax.swing.JComboBox<String> numberPlayers;
    private javax.swing.JLabel principalImage;
    private javax.swing.JPanel principalPanel;
    private javax.swing.JPanel principalPanel2;
    // End of variables declaration//GEN-END:variables

    
   
    public void searchPlayerVersus(){
        if(playersThatWillPlay.contains(labelName.getName())){
            JOptionPane.showMessageDialog(rootPane, "That player is already playing");
        }
        else{
            if(playersThatWillPlay.size() < 4){
                playersThatWillPlay.add(labelName.getText());
                numberOfPlayersSelected++; 
                JOptionPane.showMessageDialog(rootPane, labelName.getText() + " selected.");
                System.out.println(playersThatWillPlay.get(0) + " selected");
                labelplayersSelected.setText(Integer.toString(numberOfPlayersSelected));
            }
            else{   
                JOptionPane.showMessageDialog(rootPane, "You can not select more than 4 players.");
            }
        }
    }
        
}
