/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Randald
 */
public class WindowSelectionGame extends javax.swing.JFrame {
    //NavBar will be used to keep the NavBar events..
    private boolean navBar, navBar2;
    /**
     * Creates new form Load
     */
    public WindowSelectionGame() {
        initComponents();
        
        this.setExtendedState(MAXIMIZED_BOTH);  //set full size
        
        Boolean navBar = false;                 //set nav bar = false because the navBar will be close when the user start the game         
        principalPanel.setSize(0,0);            // set panel for load (0,0)
        principalPanel2.setSize(0,0);           // set panel for new game (0,0)
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalImage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        butonLoadGame = new javax.swing.JButton();
        butonNewGame = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        actualPlayerName2 = new javax.swing.JLabel();
        principalPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        principalPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        numberPlayers = new javax.swing.JComboBox<>();
        buttonNewGame = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        principalImage.setBackground(new java.awt.Color(84, 0, 255));
        principalImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/domino.jpg"))); // NOI18N
        getContentPane().add(principalImage);
        principalImage.setBounds(490, 0, 1530, 1080);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Script MT Bold", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(32, 124, 2));
        jLabel1.setText("THE DOMINO'S GAME");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 30, 280, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/load.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 300, 96, 89);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/new.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 460, 96, 95);

        butonLoadGame.setBackground(new java.awt.Color(0, 0, 0));
        butonLoadGame.setFont(new java.awt.Font("Script MT Bold", 3, 18)); // NOI18N
        butonLoadGame.setForeground(new java.awt.Color(255, 255, 255));
        butonLoadGame.setText("Load");
        butonLoadGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonLoadGameActionPerformed(evt);
            }
        });
        jPanel1.add(butonLoadGame);
        butonLoadGame.setBounds(250, 310, 91, 55);

        butonNewGame.setBackground(new java.awt.Color(0, 0, 0));
        butonNewGame.setFont(new java.awt.Font("Script MT Bold", 3, 18)); // NOI18N
        butonNewGame.setForeground(new java.awt.Color(255, 255, 255));
        butonNewGame.setText("New");
        butonNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonNewGameActionPerformed(evt);
            }
        });
        jPanel1.add(butonNewGame);
        butonNewGame.setBounds(250, 470, 91, 60);

        jLabel6.setFont(new java.awt.Font("Script MT Bold", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(32, 124, 2));
        jLabel6.setText("WELCOME ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(160, 100, 140, 40);

        actualPlayerName2.setFont(new java.awt.Font("Script MT Bold", 3, 24)); // NOI18N
        actualPlayerName2.setForeground(new java.awt.Color(32, 124, 2));
        actualPlayerName2.setText("PLAYER ");
        jPanel1.add(actualPlayerName2);
        actualPlayerName2.setBounds(160, 170, 140, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 490, 1080);

        principalPanel.setBackground(new java.awt.Color(20, 0, 169));
        principalPanel.setMaximumSize(new java.awt.Dimension(1530, 1080));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userGames.png"))); // NOI18N

        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout principalPanelLayout = new javax.swing.GroupLayout(principalPanel);
        principalPanel.setLayout(principalPanelLayout);
        principalPanelLayout.setHorizontalGroup(
            principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalPanelLayout.createSequentialGroup()
                .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(principalPanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel4))
                    .addGroup(principalPanelLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(422, Short.MAX_VALUE))
        );
        principalPanelLayout.setVerticalGroup(
            principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        getContentPane().add(principalPanel);
        principalPanel.setBounds(490, 0, 1530, 660);

        principalPanel2.setBackground(new java.awt.Color(20, 0, 169));
        principalPanel2.setMaximumSize(new java.awt.Dimension(1530, 1080));
        principalPanel2.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/check1.png"))); // NOI18N
        principalPanel2.add(jLabel7);
        jLabel7.setBounds(49, 54, 96, 96);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        numberPlayers.setBackground(new java.awt.Color(3, 105, 49));
        numberPlayers.setFont(new java.awt.Font("Script MT Bold", 1, 14)); // NOI18N
        numberPlayers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2 Players", "3 Players", "4 Players" }));

        buttonNewGame.setBackground(new java.awt.Color(3, 105, 49));
        buttonNewGame.setFont(new java.awt.Font("Script MT Bold", 1, 14)); // NOI18N
        buttonNewGame.setForeground(new java.awt.Color(255, 255, 255));
        buttonNewGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/check.png"))); // NOI18N
        buttonNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewGameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        jLabel5.setText("Select the players");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(numberPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonNewGame)
                        .addGap(47, 47, 47))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numberPlayers)
                    .addComponent(buttonNewGame, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                .addGap(131, 131, 131))
        );

        principalPanel2.add(jPanel2);
        jPanel2.setBounds(121, 168, 311, 344);

        getContentPane().add(principalPanel2);
        principalPanel2.setBounds(490, 0, 1530, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butonNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonNewGameActionPerformed
        //It check if the panel for new game is open or not
        if (navBar2 == true){                //If is open
            principalPanel2.setSize(0, 0);   //the panel for new game will change to close 
            navBar2 = false;                 //it change the NavBar 2 status
            principalPanel.setSize(0, 0);   //the panel for load game will change to close
            navBar = false;                 //it change the NavBar 1 status
        } 
        else{ //if navBar is close
            principalPanel2.setSize(550, 1080);//the panel for new game will change to Open
            navBar2 = true;                    // it change the NavBar 2 status
            principalPanel.setSize(0, 0);      //the panel for load game will change to close
            navBar = false;                    //it change the NavBar 1 status
        }
    }//GEN-LAST:event_butonNewGameActionPerformed

    private void butonLoadGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonLoadGameActionPerformed
        //It check if the panel for load game is open or not
        if (navBar == true){                //If is open the panel
            principalPanel.setSize(0, 0); //the load panel will change to close 
            navBar = false;                 //it change the NavBar status
            principalPanel2.setSize(0, 0);  //the new game panel  will change to close
            navBar2 = false;                //it change the NavBar 2 status
        } 
        else{ //if navBar is close
            principalPanel.setSize(550, 1080);//the principal panel will change to Open
            navBar = true;                   // it change the NavBar status
            principalPanel2.setSize(0, 0);   //the new game panel will change to close
            navBar2 = false;                 //it change the NavBar 2 status
        }
    }//GEN-LAST:event_butonLoadGameActionPerformed

    private void buttonNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewGameActionPerformed

        if (numberPlayers.getSelectedItem() == "2 Players") {          //check if is two players selected
            ListPlayersGaming.getInstance().setNumberOfGamers(2);   
            ListPlayersGaming.getInstance().makeListofTwoPlayers();    //add user 1 information
            WindowStartGame newWindows = new WindowStartGame();        //close This windows and go to Start Game Windows 
            newWindows.setVisible(true);                               //set visible the new windows
            this.dispose();                                            //Destroy the actual windows
        } 
        else if (numberPlayers.getSelectedItem() == "3 Players") {     //check if is tree players selected
            ListPlayersGaming.getInstance().setNumberOfGamers(3);
            ListPlayersGaming.getInstance().makeListofThreePlayers();  //add user 1 information
            WindowStartGame newWindows = new WindowStartGame();        //close This windows and go to Start Game Windows 
            newWindows.setVisible(true);                               //set visible the new windows
            this.dispose();                                            //Destroy the actual windows
        } 
        else {
            ListPlayersGaming.getInstance().setNumberOfGamers(4);
            ListPlayersGaming.getInstance().makeListofFourPlayers();
            WindowStartGame newWindows = new WindowStartGame();        //close This windows and go to Start Game Windows 
            newWindows.setVisible(true);                               //set visible the new windows
            this.dispose();                                            //Destroy the actual windows
        }
        
    }//GEN-LAST:event_buttonNewGameActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actualPlayerName2;
    private javax.swing.JButton butonLoadGame;
    private javax.swing.JButton butonNewGame;
    private javax.swing.JButton buttonNewGame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> numberPlayers;
    private javax.swing.JLabel principalImage;
    private javax.swing.JPanel principalPanel;
    private javax.swing.JPanel principalPanel2;
    // End of variables declaration//GEN-END:variables
}
