/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import javax.swing.JOptionPane;

/**
 *
 * @author Fabián
 */
public class WindowAdmin extends javax.swing.JFrame {

    /**
     * Creates new form WindowAdmin
     */
    public WindowAdmin() {
        super("Domino's Administration Menu");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        labelResult = new javax.swing.JLabel();
        buttonModifyUser = new javax.swing.JButton();
        TextFieldPassword = new javax.swing.JTextField();
        labelTextPassword = new javax.swing.JLabel();
        labelTextName = new javax.swing.JLabel();
        TextFieldName = new javax.swing.JTextField();
        buttonAddUser = new javax.swing.JButton();
        labelUserToEdit = new javax.swing.JLabel();
        labelNewName = new javax.swing.JLabel();
        labelNewPassword = new javax.swing.JLabel();
        TextFieldUserToEdit = new javax.swing.JTextField();
        TextFieldNewName = new javax.swing.JTextField();
        TextFieldNewPassword = new javax.swing.JTextField();
        changeWins = new javax.swing.JLabel();
        TextFieldChangeWins = new javax.swing.JTextField();
        buttonSearch = new javax.swing.JButton();
        buttonBack = new javax.swing.JButton();
        labelSearchUser = new javax.swing.JLabel();
        TextFieldUserDelete = new javax.swing.JTextField();
        labelTextResult = new javax.swing.JLabel();
        buttonDeleteUser = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        buttonLeft = new javax.swing.JButton();
        buttonStart = new javax.swing.JButton();
        buttonEnd = new javax.swing.JButton();
        buttonRight = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progra1/Images/dominobbbb.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(labelResult);
        labelResult.setBounds(360, 330, 130, 19);

        buttonModifyUser.setText("Edit User");
        buttonModifyUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModifyUserActionPerformed(evt);
            }
        });
        getContentPane().add(buttonModifyUser);
        buttonModifyUser.setBounds(110, 340, 80, 25);
        getContentPane().add(TextFieldPassword);
        TextFieldPassword.setBounds(70, 90, 120, 19);

        labelTextPassword.setText("Password:");
        getContentPane().add(labelTextPassword);
        labelTextPassword.setBounds(10, 90, 53, 15);

        labelTextName.setText("Name:");
        getContentPane().add(labelTextName);
        labelTextName.setBounds(20, 57, 30, 15);
        getContentPane().add(TextFieldName);
        TextFieldName.setBounds(68, 55, 120, 19);

        buttonAddUser.setText("Add user");
        buttonAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddUserActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAddUser);
        buttonAddUser.setBounds(100, 120, 80, 25);

        labelUserToEdit.setText("User to edit:");
        getContentPane().add(labelUserToEdit);
        labelUserToEdit.setBounds(30, 220, 58, 15);

        labelNewName.setText("New Name :");
        getContentPane().add(labelNewName);
        labelNewName.setBounds(30, 250, 59, 15);

        labelNewPassword.setText("New Password:");
        getContentPane().add(labelNewPassword);
        labelNewPassword.setBounds(10, 280, 79, 15);
        getContentPane().add(TextFieldUserToEdit);
        TextFieldUserToEdit.setBounds(110, 220, 80, 19);
        getContentPane().add(TextFieldNewName);
        TextFieldNewName.setBounds(110, 250, 80, 19);
        getContentPane().add(TextFieldNewPassword);
        TextFieldNewPassword.setBounds(110, 280, 80, 19);

        changeWins.setText("Change Wins to:");
        getContentPane().add(changeWins);
        changeWins.setBounds(10, 310, 79, 15);
        getContentPane().add(TextFieldChangeWins);
        TextFieldChangeWins.setBounds(110, 310, 80, 19);

        buttonSearch.setText("Search");
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSearch);
        buttonSearch.setBounds(360, 290, 90, 25);

        buttonBack.setText("Back");
        buttonBack.setToolTipText("");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });
        getContentPane().add(buttonBack);
        buttonBack.setBounds(30, 390, 60, 30);

        labelSearchUser.setText("Search user:");
        getContentPane().add(labelSearchUser);
        labelSearchUser.setBounds(290, 260, 63, 15);

        TextFieldUserDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldUserDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(TextFieldUserDelete);
        TextFieldUserDelete.setBounds(360, 260, 89, 19);

        labelTextResult.setText("Password:");
        getContentPane().add(labelTextResult);
        labelTextResult.setBounds(300, 330, 53, 15);

        buttonDeleteUser.setText("Delete user");
        buttonDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteUserActionPerformed(evt);
            }
        });
        getContentPane().add(buttonDeleteUser);
        buttonDeleteUser.setBounds(360, 360, 89, 25);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText(" Registered games");

        buttonLeft.setText("<<");

        buttonStart.setText("Start");

        buttonEnd.setText("End");

        buttonRight.setText(">>");

        jList1.setFont(new java.awt.Font("Dialog", 2, 11)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Date", "Winner" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(buttonLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRight)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(94, 94, 94))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLeft)
                    .addComponent(buttonStart)
                    .addComponent(buttonEnd)
                    .addComponent(buttonRight))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(280, 40, 280, 150);

        jButton1.setText("See");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 430, 53, 25);

        jLabel1.setText("Number of players");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 400, 89, 15);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldUserDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldUserDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldUserDeleteActionPerformed

    private void buttonDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteUserActionPerformed
        // TODO add your handling code here:
        if(TextFieldUserDelete.getText().isEmpty())
            JOptionPane.showMessageDialog(rootPane, "Empty field");
        else{
            String name = TextFieldUserDelete.getText();
            String deleteMethod = PlayersList.getInstance().deletePlayer(name);
            TextFieldUserDelete.setText("");
            JOptionPane.showMessageDialog(rootPane, deleteMethod);
       }
    }//GEN-LAST:event_buttonDeleteUserActionPerformed

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        // TODO add your handling code here:
        if(TextFieldUserDelete.getText().isEmpty())
            JOptionPane.showMessageDialog(rootPane, "Type a player to eliminate");
        else{
            Player userX = PlayersList.getInstance().searchPlayer(TextFieldUserDelete.getText());
            if(userX == null)
                labelResult.setText("No matches found");
            else{
                labelResult.setText(userX.getPassword());
            }
        }
        
    }//GEN-LAST:event_buttonSearchActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:
        WindowLogin wLogin = new WindowLogin();
        wLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddUserActionPerformed
        // TODO add your handling code here:
        if(TextFieldName.getText().isEmpty() | TextFieldPassword.getText().isEmpty())
            JOptionPane.showMessageDialog(rootPane, "Empty field");
        else{
            String nameX = TextFieldName.getText();
            String passwordX = TextFieldPassword.getText();
            PlayersList.getInstance().insertFinal(nameX, passwordX, 0);
            TextFieldName.setText("");
            TextFieldPassword.setText("");
            JOptionPane.showMessageDialog(rootPane, "Player " + nameX + "successfully added to the system.");
        }
    }//GEN-LAST:event_buttonAddUserActionPerformed

    private void buttonModifyUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModifyUserActionPerformed
        // TODO add your handling code here:
        if(TextFieldUserToEdit.getText().isEmpty() | TextFieldNewName.getText().isEmpty() | TextFieldNewPassword.getText().isEmpty() |  TextFieldChangeWins.getText().isEmpty())
            JOptionPane.showMessageDialog(rootPane, "Empty field");
        else{
            String name = TextFieldUserToEdit.getText();
            String newName = TextFieldNewName.getText();
            String password = TextFieldNewPassword.getText();
            int wins = Integer.parseInt(TextFieldChangeWins.getText());
            PlayersList.getInstance().editPlayer(name, newName, password, wins);
            TextFieldUserToEdit.setText("");
            TextFieldNewName.setText("");
            TextFieldNewPassword.setText("");
            TextFieldChangeWins.setText("");
            JOptionPane.showMessageDialog(rootPane, "Player " + name + " successfully edited.");
        }
    }//GEN-LAST:event_buttonModifyUserActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jLabel1.setText(Integer.toString(PlayersList.getInstance().lenghtList()));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFieldChangeWins;
    private javax.swing.JTextField TextFieldName;
    private javax.swing.JTextField TextFieldNewName;
    private javax.swing.JTextField TextFieldNewPassword;
    private javax.swing.JTextField TextFieldPassword;
    private javax.swing.JTextField TextFieldUserDelete;
    private javax.swing.JTextField TextFieldUserToEdit;
    private javax.swing.JButton buttonAddUser;
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonDeleteUser;
    private javax.swing.JButton buttonEnd;
    private javax.swing.JButton buttonLeft;
    private javax.swing.JButton buttonModifyUser;
    private javax.swing.JButton buttonRight;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JButton buttonStart;
    private javax.swing.JLabel changeWins;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNewName;
    private javax.swing.JLabel labelNewPassword;
    private javax.swing.JLabel labelResult;
    private javax.swing.JLabel labelSearchUser;
    private javax.swing.JLabel labelTextName;
    private javax.swing.JLabel labelTextPassword;
    private javax.swing.JLabel labelTextResult;
    private javax.swing.JLabel labelUserToEdit;
    // End of variables declaration//GEN-END:variables
}
